README.md
Added class description and added contact/registration information.
=> Updated  class description and contact information

homework/DeclaringVariables.java, homework/VarExercise.java, src/Examples/ArithmeticDemo.java, src/Examples/UnaryDemo.java
Chapter 2 homework and example code.
=> Chapter2-Examples and Homework

src/HellowWorld/HelloWorld.java, src/HellowWorld/HelloWorld.java~, src/HellowWorld/HelloWorld2.java, src/HellowWorld/HelloWorld2.java~, src/HellowWorld/Produce.java, src/HellowWorld/wakeUpCall.java
Introduced the keyword "new" to instantiate objects.  Added more classes.  Refactored HelloWord2.
=> Introduced Static vs Non-Static Objects

homework/aj-homework/DeclaringVariables.java, homework/aj-homework/Echo.java, homework/aj-homework/VarExercise.java
=> Class exercise

homework/cc-homework/DreamGroceryShop.java, homework/cc-homework/GroceryProgram.java
I attempted to create a grocercy store program simulation. While my code complied clean, it did not loop as expected.
=> While loop/Scanner Homework

homework/aj-homework/WhosLineIsItWhileLooping.java, homework/aj-homework/WhosName2.java
Today's date; variables and operators.
=> DateExercise

homework/aj-homework/WhosLineIsItWhileLooping.java, homework/aj-homework/WhosName2.java
=> WhosNameWhileLooping

homework/cc-homework/GroceryProgram.java, homework/cc-homework/WhatIsInStock.java~
Reading canned goods inventory and adding into grocery program
=> Reading files HW

homework/cc-homework/Department.java, homework/cc-homework/babyessentials/BabyEssentialsDept.java, homework/cc-homework/garden/GardenDept.java, homework/cc-homework/petcare/PetCareDept.java, homework/cc-homework/toiletries/ToiletryDept.java
created 4 new packages for Super store project and created a new data member for util.department
=> Introducing 4 new packages to Super Store project

projects/src/main/java/com/usi/src/electronics/ElectronicsDept.java
Added the Electronics Department
=> Added new Department

projects/src/main/java/com/usi/src/books/.gitignore, projects/src/main/java/com/usi/src/books/BookDept.java, projects/src/main/java/com/usi/src/fragrance/.gitignore, projects/src/main/java/com/usi/src/fragrance/FragranceDept.java, projects/src/main/java/com/usi/src/resources/BabyEssentials.txt, projects/src/main/java/com/usi/src/stationary/.gitignore, projects/src/main/java/com/usi/src/stationary/StationaryDept.java
Added a fragrance, book, and stationary dept.
=> 3 new depts

projects/src/main/java/com/usi/src/resources/Automotive.txt
=> Updated Automotive txt

projects/src/main/java/com/usi/src/bikes/.gitignore, projects/src/main/java/com/usi/src/furniture/.gitignore, projects/src/main/java/com/usi/src/haircare/.gitignore, projects/src/main/java/com/usi/src/housewares/.gitignore, projects/src/main/java/com/usi/src/plantbase/.gitignore, projects/src/main/java/com/usi/src/resources/Automotive.txt, projects/src/main/java/com/usi/src/resources/BabyEssentials.txt, projects/src/main/java/com/usi/src/resources/Bakery.txt, projects/src/main/java/com/usi/src/shoe/.gitignore, projects/src/main/java/com/usi/src/toys/.gitignore, projects/src/main/java/com/usi/src/util/.gitignore, projects/src/main/java/com/usi/src/util/StoreConstants.java
Added to Automotive and Baby Essentials
=> Super store Record models

projects/src/main/java/com/usi/src/resources/Automotive.txt, projects/src/main/java/com/usi/src/resources/BabyEssentials.txt, projects/src/main/java/com/usi/src/resources/Beverages.txt
=> Replaced Pipes

projects/src/main/java/com/usi/src/haircare/HairCareDept.java, projects/src/main/java/com/usi/src/haircare/HaircareProd.java
=> Haircare stuff

homework/aj-homework/Furniture.txt, projects/src/main/java/com/usi/src/bakery/BakeryDept.java, projects/src/main/java/com/usi/src/bakery/BakeryProd.java, projects/src/main/java/com/usi/src/cleaningsupplies/CleaningSuppliesProd.java, projects/src/main/java/com/usi/src/clothes/ClothesDept.java, projects/src/main/java/com/usi/src/clothes/ClothesProd.java, projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/linen/LinenDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyProd.java, projects/src/main/java/com/usi/src/resources/Bakery.txt, projects/src/main/java/com/usi/src/resources/CleaningSupplies.txt, projects/src/main/java/com/usi/src/resources/Clothes.txt, projects/src/main/java/com/usi/src/resources/Furniture.txt, projects/src/main/java/com/usi/src/resources/Meat.txt, projects/src/main/java/com/usi/src/resources/Pharmacy.txt, projects/src/main/java/com/usi/src/resources/PlantBase.txt, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/util/StoreConstants.java
Start To Finish Bakery and 8 .txt files
=> Start to finish bakery

projects/src/main/java/com/usi/src/resources/Deli.txt, projects/src/main/java/com/usi/src/resources/Fragrance.txt, projects/src/main/java/com/usi/src/resources/FrozenFoods.txt, projects/src/main/java/com/usi/src/resources/Luggage.txt, projects/src/main/java/com/usi/src/resources/Produce.txt
Created Txtfiles for:
Luggage
FrozenFoods
Produce
Fragrance
Luggage
=> Text Files Created

projects/src/main/java/com/usi/src/deli/DeliDept.java, projects/src/main/java/com/usi/src/deli/DeliProd.java, projects/src/main/java/com/usi/src/fragrance/FragranceDept.java, projects/src/main/java/com/usi/src/fragrance/FragranceProd.java
Start to Finish Fragrance and Deli
=> Fragrance and Deli

projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/util/StoreConstants.java
addtl. changes made to open depts.
=> Additional changes to opened depts

projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/fragrance/FragranceDept.java, projects/src/main/java/com/usi/src/fragrance/FragranceProd.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/produce/ProduceProd.java
fix to fragrance and produce
new up and import to Superstore
=> Fix to Fragrance

projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/deli/DeliDept.java, projects/src/main/java/com/usi/src/deli/DeliProd.java, projects/src/main/java/com/usi/src/fragrance/FragranceDept.java, projects/src/main/java/com/usi/src/frozenfoods/FrozenFoodsDept.java, projects/src/main/java/com/usi/src/resources/Fragrance.txt
=> Fragance and Deli

Docs/Phase 2 Product Completion Assignments, projects/src/main/java/com/usi/src/bedding/.gitignore, projects/src/main/java/com/usi/src/bedding/BeddingDept.java, projects/src/main/java/com/usi/src/bedding/BeddingProd.java, projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/resources/Bedding.txt, projects/src/main/java/com/usi/src/resources/Luggage.txt, projects/src/main/java/com/usi/src/resources/Toiletries.txt, projects/src/main/java/com/usi/src/toiletries/.gitignore, projects/src/main/java/com/usi/src/toiletries/ToiletryDept.java, projects/src/main/java/com/usi/src/toiletries/ToiletryProd.java, projects/src/main/java/com/usi/src/util/.gitignore, projects/src/main/java/com/usi/src/util/StoreConstants.java
Opened Toiletries Dept and Bedding Dept. Created Product class for both Departments. Loaded and unloaded trucks for both Depts. Created data model txt files with inventory for both Dept. Ran Debugger clean for both Depts
Departments completed
Books
Bedding
Beverages
Baby Essentials
Canned Goods
Electronics
Garden
Petcare
Pantry
Toiletries
Tupperware
=> Opened 2 new Depts

projects/src/main/java/com/usi/src/resources/FrozenFoods.txt, projects/src/main/java/com/usi/src/resources/Luggage.txt
FROZEN FOOD
LUGGAGE
ENUMS CORRECTED
=> CORRECTED TXT

projects/src/main/java/com/usi/src/resources/Tupperware.txt, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareProd.java, projects/src/main/java/com/usi/src/util/StoreConstants.java
Minor data file adjustments
-completed dept
-completed prod
-store constant to load truck
-instantiated
-debugger ran clean; no errors with 6 crates and 6 types of prod
=> Comitting  tupperware dept, prod and data txt files

projects/src/main/java/com/usi/src/customerservice/.gitignore, projects/src/main/java/com/usi/src/customerservice/Reciept.java, projects/src/main/java/com/usi/src/resources/Tupperware.txt, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareProd.java, projects/src/main/java/com/usi/src/util/StoreConstants.java
=> Receipt class created

projects/src/main/java/com/usi/src/customerservice/Reciept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareProd.java, projects/src/main/java/com/usi/src/util/StoreConstants.java
Attempting to work on Receipt class 
Imported Scanner to scan in responses from Store patrons
Instantiated Store Printer to connect each individual receipt to the store printer
Created if else statements for Receipt class
Just an attempt at laying some code so i can generate some questions for class.
=> Working on Reciept Class

projects/src/main/java/com/usi/src/resources/Membership Card.txt
blueprint for membership txt file
=> Create Membership Card.txt

projects/src/main/java/com/usi/src/smartcart/ShoppingCart.java, projects/src/main/java/com/usi/src/util/StoreConstants.java
Store Constant Changes
- removed vegtable dept
- moved leopard and tortise "colors" to color enum
=> Store Constant Changes

projects/src/main/java/com/usi/src/resources/Membership Card.txt, projects/src/main/java/com/usi/src/util/StoreConstants.java
I made a few small changes to the membership txt file
Added a note to Store Constants with an enum question
Added to Membership sign up which I will not submit at this time due to errors.
=> Membership info and change

projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/resources/Dairy.txt, projects/src/main/java/com/usi/src/resources/Shoe.txt, projects/src/main/java/com/usi/src/smartcart/Receipt.java
Working on the prototype for emailReceipt Method in Receipt class.
=> email Receipt prototype

projects/src/main/java/com/usi/src/customerservice/MembershipSignUp.java, projects/src/main/java/com/usi/src/resources/Membership Card.txt
fix to txt file
and membership sign up
=> Membership card adjustment

projects/src/main/java/com/usi/src/customerservice/SuperStore.java
=> Update Super store

projects/src/main/java/com/usi/src/smartcart/CheckOut.java
=> Created Check Out Class

projects/src/main/java/com/usi/src/customerservice/SuperStore.java, projects/src/main/java/com/usi/src/smartcart/Receipt.java, projects/src/main/java/com/usi/src/util/Product.java, projects/src/main/java/com/usi/src/util/StorePrinter.java
Refactored the format for Reciept printable
Instantiated Customer class ( Membership Id )
Worked on new method in Super Store for departmentClosed (in the event a department has no products loaded.
=> Refactoring

projects/src/main/java/com/usi/src/smartcart/LED.java
Beginning of LED
- created LED class to extend Store Printer
- will created a method but waiting to find out more about the
Prototype created.
- method to be created will eventualy initiate LED functions with the
Smart Cart and Store Printer.
=> Created LED.java Class to extend Store Printer

projects/src/main/java/com/usi/src/resources/MembershipCard.txt
udated field in txt file
change from middle initial to middle name
=> updated field in tx

projects/src/main/java/com/usi/src/customerservice/Customer.java
create method for shopping cart
new up cart
get and return product list
=> Customer introduce shoppingcart

projects/src/main/java/com/usi/src/resources/MembershipCard.txt
=> Membership card

projects/src/main/java/com/usi/src/resources/MembershipCard.txt, projects/src/main/java/com/usi/src/resources/PrescriptionEyeware.txt
Membership Card txt
- added comma
- added state
- added zip code; please correct if this is not your true zip code Roxanne
=> Membership Card  txt

projects/src/main/java/com/usi/src/electronics/ElectronicsDept.java, projects/src/main/java/com/usi/src/pantry/PantryDept.java, projects/src/main/java/com/usi/src/petcare/PetcareDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java, projects/src/main/java/com/usi/src/plantbase/PlantBaseDept.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareDept.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/resources/Luggage.txt, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/shoe/ShoeDept.java, projects/src/main/java/com/usi/src/stationary/StationaryDept.java, projects/src/main/java/com/usi/src/toiletries/ToiletryDept.java, projects/src/main/java/com/usi/src/toys/ToysDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java
Added new code for pantry thru tupperware
=> Added new code/buttons for pantry thru tupperware

projects/src/main/java/com/usi/src/pantry/PantryProd.java, projects/src/main/java/com/usi/src/petcare/PetcareProd.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyProd.java, projects/src/main/java/com/usi/src/plantbase/PlantBaseProd.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareProd.java, projects/src/main/java/com/usi/src/produce/ProduceProd.java, projects/src/main/java/com/usi/src/seafood/SeafoodProd.java, projects/src/main/java/com/usi/src/shoe/ShoeProd.java, projects/src/main/java/com/usi/src/stationary/StationaryProd.java, projects/src/main/java/com/usi/src/toiletries/ToiletryProd.java, projects/src/main/java/com/usi/src/toys/ToysProd.java, projects/src/main/java/com/usi/src/tupperware/TupperwareProd.java
added .trim() to all dept prod
=> added .trim()

projects/src/main/java/com/usi/src/bedding/BeddingDept.java
Added Get Scene method above javafx coding and all the errors went away
also changed the scene name to match the scene for the department scene was happening in. ALl errors should be clear
=> Bedding Dept Fix

projects/src/main/java/com/usi/src/cannedgoods/CannedGoodsDept.java, projects/src/main/java/com/usi/src/cleaningsupplies/CleaningSuppliesDept.java, projects/src/main/java/com/usi/src/clothes/ClothesDept.java, projects/src/main/java/com/usi/src/dairy/DairyDept.java, projects/src/main/java/com/usi/src/deli/DeliDept.java
canned goods
dairy
deli
clothes
cleaning supplies
=> code added to update 5 depts

projects/src/main/java/com/usi/src/bedding/BeddingDept.java
=>  Update 2 bedding

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java
Updated Pharmacy Greeting to view View Cart Method
- I feel like the Home Alone kid right now! Looking for everything to make this work but it's still a mess! LOL!!!
=> Updated Pharmacy Greeting to view View Cart Method

projects/src/main/java/com/usi/src/smartcart/Receipt.java
Fixed for each loop in Receipt prod list
=> Receipt work

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/util/Product.java
product details added
format adjusted
=> Add Details to products in Greeting Dept

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/resources/MembershipCard.txt
Wanted indeed!
Added and corrected Member Data
=> "Unwanted?" of course not!

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/resources/CannedGoods.txt
adjusted txt to greeting pop up
added txt to canned goods details
=> Text Formating

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/resources/BabyEssentials.txt, projects/src/main/java/com/usi/src/resources/CannedGoods.txt
mp4 correction for book dept.
ingred add to canned foods and baby essentials
border adjustment
=> mp4 adjustment txt ingred

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/smartcart/Receipt.java, projects/src/main/java/com/usi/src/smartcart/StoreCheckOut.java
Tied up loose ends connecting card method for change pop up, did the same for the receipt. Will be doing a total restructure of reciept node print out.
=> Change pop up

projects/src/main/java/com/usi/src/customerservice/Greeting.java
added label, scrollpane, textbox, to contain text
=> Description Ingrediants Textbox format

projects/src/main/java/com/usi/src/books/BookDept.java, projects/src/main/java/com/usi/src/cannedgoods/CannedGoodsDept.java, projects/src/main/java/com/usi/src/cleaningsupplies/CleaningSuppliesDept.java, projects/src/main/java/com/usi/src/clothes/ClothesDept.java
Making style changes to
Books
Canned Goods
Cleaning
and Clothes
=> Colors and Fonts

projects/src/main/java/com/usi/src/smartcart/Receipt.java, projects/src/main/java/com/usi/src/util/NodePrinter.java
=> Working on printing

projects/src/main/java/com/usi/src/pantry/PantryDept.java, projects/src/main/java/com/usi/src/petcare/PetcareDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java, projects/src/main/java/com/usi/src/plantbase/PlantBaseDept.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareDept.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/shoe/ShoeDept.java, projects/src/main/java/com/usi/src/stationary/StationaryDept.java, projects/src/main/java/com/usi/src/toiletries/ToiletryDept.java, projects/src/main/java/com/usi/src/toys/ToysDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java
Dept changes, pantry to tupperware
- changed all depts image view to 400
- removed all depts String goIn thru
eBox.getChildren
- changed all depts Scene eScene from 600, 650 to
500,550
=> Dept image view, shop text and scene eVBox

projects/src/main/java/com/usi/src/babyessentials/BabyEssentialsDept.java, projects/src/main/java/com/usi/src/bakery/BakeryDept.java, projects/src/main/java/com/usi/src/bedding/BeddingDept.java, projects/src/main/java/com/usi/src/beverages/BeveragesDept.java, projects/src/main/java/com/usi/src/bikes/BikesDept.java, projects/src/main/java/com/usi/src/books/BookDept.java, projects/src/main/java/com/usi/src/cannedgoods/CannedGoodsDept.java, projects/src/main/java/com/usi/src/cleaningsupplies/CleaningSuppliesDept.java, projects/src/main/java/com/usi/src/clothes/ClothesDept.java, projects/src/main/java/com/usi/src/dairy/DairyDept.java, projects/src/main/java/com/usi/src/deli/DeliDept.java
Updated deptartments a-d to reflect consistant scene height and with.
minor font and color changes to dept.s
=> Department A-D Updated

projects/src/main/java/com/usi/src/books/BookDept.java, projects/src/main/java/com/usi/src/clothes/ClothesDept.java, projects/src/main/java/com/usi/src/customerservice/Greeting.java
Book - VBox size
Clothing - image size change
Greeting- fixed typo in code
=> Dept. Adjustments

projects/src/main/java/com/usi/src/electronics/ElectronicsDept.java, projects/src/main/java/com/usi/src/fragrance/FragranceDept.java, projects/src/main/java/com/usi/src/frozenfoods/FrozenFoodsDept.java, projects/src/main/java/com/usi/src/furniture/FurnitureDept.java, projects/src/main/java/com/usi/src/garden/GardenDept.java, projects/src/main/java/com/usi/src/haircare/HairCareDept.java, projects/src/main/java/com/usi/src/housewares/HousewaresDept.java, projects/src/main/java/com/usi/src/linen/LinenDept.java, projects/src/main/java/com/usi/src/luggage/LuggageDept.java, projects/src/main/java/com/usi/src/meat/MeatDept.java, projects/src/main/java/com/usi/src/smartcart/Receipt.java
Beginning to add CSS borders to Dept Images for extra styling.
Also working on refactoring Reciept code to print our Brand name instead of Product name to differentiate between products when adding up quantity.
=> Work In Progress

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/pantry/PantryDept.java, projects/src/main/java/com/usi/src/petcare/PetcareDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java, projects/src/main/java/com/usi/src/plantbase/PlantBaseDept.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareDept.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/shoe/ShoeDept.java, projects/src/main/java/com/usi/src/stationary/StationaryDept.java, projects/src/main/java/com/usi/src/toiletries/ToiletryDept.java, projects/src/main/java/com/usi/src/toys/ToysDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java
Changed x/y co ordinances in Greeting so that the view cart, dept and checkout buttons would be more visible in all depts.
x from 50 to 60
y from 80 to 40
Added the displayDepts();  in Greeting to return an new membership window signup after the save button has been selected.
Added the java.io.File class/code to the pantry through tupperware depts to adjust the .png files and directories.
=> Dept cleaning

projects/src/main/java/com/usi/src/pantry/PantryDept.java, projects/src/main/java/com/usi/src/petcare/PetcareDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java, projects/src/main/java/com/usi/src/plantbase/PlantBaseDept.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareDept.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/shoe/ShoeDept.java, projects/src/main/java/com/usi/src/stationary/StationaryDept.java, projects/src/main/java/com/usi/src/toiletries/ToiletryDept.java, projects/src/main/java/com/usi/src/toys/ToysDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java
Changed all depts image view height from 200 to 100 so that all of the depts from pantry to tupperware will view consistently.
=> Changing image view height

projects/src/main/java/com/usi/src/pantry/PantryDept.java, projects/src/main/java/com/usi/src/petcare/PetcareDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareDept.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/shoe/ShoeDept.java, projects/src/main/java/com/usi/src/toys/ToysDept.java
Curtailed text to fit for pantry, petcare, pharmacy, eyeware, produce, seafood, shoe and toys depts.
=> Curtailed text

projects/src/main/java/com/usi/src/babyessentials/BabyEssentialsDept.java, projects/src/main/java/com/usi/src/bakery/BakeryDept.java, projects/src/main/java/com/usi/src/dairy/DairyDept.java, projects/src/main/java/com/usi/src/resources/BabyEssentials.txt
slight modifications to code to produce images
and get welcome signs working
=> Bakery Baby Dairy

projects/src/main/java/com/usi/src/customerservice/Greeting.java, projects/src/main/java/com/usi/src/smartcart/Receipt.java, projects/src/main/java/com/usi/src/smartcart/StoreCheckOut.java
Reworked EmailReciept code from sendEmail in examples. Added code to attact pdf. Cannot figure out how to connect code to send email button.
=> EmailReciept

projects/src/main/java/com/usi/src/electronics/ElectronicsDept.java, projects/src/main/java/com/usi/src/healthandbeauty/HealthAndBeautyDept.java, projects/src/main/java/com/usi/src/smartcart/Receipt.java
Worked on if statement for Dept closures due to lack of products. Not sure how to make the VBox connect with the Scene in an if statement.
Also Figure out overlay of pictures for Health and Beauty Dept. Still working on Image alignment.
Lastly changed some of the lines in the  Receipt display to do a bit of a different look.
=> Dept CLosed

projects/src/main/java/com/usi/src/bakery/BakeryDept.java
=> Border Test

projects/src/main/java/com/usi/src/babyessentials/BabyEssentialsDept.java, projects/src/main/java/com/usi/src/bakery/BakeryDept.java, projects/src/main/java/com/usi/src/bedding/BeddingDept.java, projects/src/main/java/com/usi/src/beverages/BeveragesDept.java, projects/src/main/java/com/usi/src/bikes/BikesDept.java, projects/src/main/java/com/usi/src/books/BookDept.java
Code for skipped images in:
BabyEssential
Bedding
Beverages
Bikes
Books
Decorative touchs to Bakery
=> Code for skipped images plus

projects/src/main/java/com/usi/src/pantry/PantryDept.java, projects/src/main/java/com/usi/src/petcare/PetcareDept.java, projects/src/main/java/com/usi/src/pharmacy/PharmacyDept.java, projects/src/main/java/com/usi/src/plantbase/PlantBaseDept.java, projects/src/main/java/com/usi/src/prescriptioneyeware/PrescriptionEyewareDept.java, projects/src/main/java/com/usi/src/produce/ProduceDept.java, projects/src/main/java/com/usi/src/seafood/SeafoodDept.java, projects/src/main/java/com/usi/src/shoe/ShoeDept.java, projects/src/main/java/com/usi/src/stationary/StationaryDept.java, projects/src/main/java/com/usi/src/toiletries/ToiletryDept.java, projects/src/main/java/com/usi/src/toys/ToysDept.java, projects/src/main/java/com/usi/src/tupperware/TupperwareDept.java
Adding CSS to Pantry to Tupperware...keeping it REAL simple right not guys. I'll see everyone on Tuesday! 
Blessings and Favor to you ALL!
=> Adding CSS

projects/src/main/java/com/usi/src/cannedgoods/CannedGoodsDept.java
=> Canned Goods

projects/src/main/java/com/usi/src/deli/DeliDept.java
=> Deli border

projects/src/main/java/com/usi/src/babyessentials/BabyEssentialsDept.java, projects/src/main/java/com/usi/src/cannedgoods/CannedGoodsDept.java, projects/src/main/java/com/usi/src/cleaningsupplies/CleaningSuppliesDept.java, projects/src/main/java/com/usi/src/clothes/ClothesDept.java, projects/src/main/java/com/usi/src/furniture/FurnitureDept.java
=> Final Borders

projects/src/main/java/com/usi/src/electronics/ElectronicsDept.java, projects/src/main/java/com/usi/src/fragrance/FragranceDept.java, projects/src/main/java/com/usi/src/frozenfoods/FrozenFoodsDept.java, projects/src/main/java/com/usi/src/furniture/FurnitureDept.java, projects/src/main/java/com/usi/src/garden/GardenDept.java, projects/src/main/java/com/usi/src/haircare/HairCareDept.java, projects/src/main/java/com/usi/src/healthandbeauty/HealthAndBeautyDept.java, projects/src/main/java/com/usi/src/housewares/HousewaresDept.java, projects/src/main/java/com/usi/src/linen/LinenDept.java, projects/src/main/java/com/usi/src/luggage/LuggageDept.java, projects/src/main/java/com/usi/src/meat/MeatDept.java
Switching over to LoadDb in depts e-m
=> Accessing Data base

projects/src/main/java/com/usi/src/resources/SQL/MEMEBERSHIP_INSERTS_EXAMPLE.sql
=> SQL-INSERT-INTO
